import StudyPage from '../components/StudyPage';
import HtmlLab from '../components/HtmlLab';

const table = (head: string[], rows: Array<React.ReactNode[]>) => <div className="table-wrap"><table className="sti-table"><thead><tr>{head.map((cell) => <th key={cell}>{cell}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>;
const code = (text: string) => <pre className="sql-block">{text}</pre>;
export default function CssPage() { return <StudyPage accent="#2196f3" glow="#2196f340" badge="CSS3 · STI" title="CSS3 — Rappel" subtitle="Sélecteurs, propriétés, mise en page et responsive design" toc={[{id:'bases',label:'Bases'},{id:'selecteurs',label:'Sélecteurs'},{id:'box',label:'Box model'},{id:'flex',label:'Flexbox'},{id:'grid',label:'Grid'}]} sections={[
{id:'bases',icon:'1',title:'Inclure du CSS',content:<>{table(['Méthode','Syntaxe','Usage'],[[<code>inline</code>,<code>style="color: red"</code>,'Petite modification locale'],[<code>interne</code>,<code>&lt;style&gt;...&lt;/style&gt;</code>,'Une page'],[<code>externe</code>,<code>&lt;link rel="stylesheet" href="style.css"&gt;</code>,'Méthode recommandée']])}{code('body {\n  font-family: Arial, sans-serif;\n  color: #222;\n  background: #f5f7fb;\n}')}</>},
{id:'selecteurs',icon:'2',title:'Sélecteurs courants',content:<>{table(['Sélecteur','Cible','Exemple'],[[<code>p</code>,'Toutes les balises p','p { color: blue; }'],[<code>.classe</code>,'Éléments portant une classe','.card { padding: 1rem; }'],[<code>#identifiant</code>,'Élément portant un id','#menu { display: flex; }'],[<code>parent enfant</code>,'Descendant','nav a { text-decoration: none; }'],[<code>:hover</code>,'État au survol','button:hover { opacity: .8; }']])}<HtmlLab initialCode={'<style>\n.card { color: #2196f3; padding: 12px; border: 1px solid currentColor; border-radius: 8px; }\n.card:hover { background: #e3f2fd; }\n</style>\n<div class="card">Survolez cette carte</div>'} /></>},
{id:'box',icon:'3',title:'Le modèle de boîte',content:<>{table(['Propriété','Rôle'],[[<code>width / height</code>,'Largeur et hauteur du contenu'],[<code>padding</code>,'Espace intérieur'],[<code>border</code>,'Bordure'],[<code>margin</code>,'Espace extérieur'],[<code>box-sizing: border-box</code>,'Inclut padding et border dans la taille']])}{code('.card {\n  box-sizing: border-box;\n  width: 320px;\n  padding: 24px;\n  border: 1px solid #2196f3;\n  margin: 16px auto;\n}')}</>},
{id:'flex',icon:'4',title:'Flexbox',content:<>{table(['Propriété','Valeurs fréquentes'],[[<code>display</code>,<code>flex</code>],[<code>flex-direction</code>,<code>row · column</code>],[<code>justify-content</code>,<code>start · center · space-between</code>],[<code>align-items</code>,<code>stretch · center</code>],[<code>gap</code>,<code>8px · 1rem</code>]])}<HtmlLab initialCode={'<style>\n.row { display: flex; gap: 8px; justify-content: center; }\n.item { padding: 14px; background: #2196f3; color: white; border-radius: 8px; }\n</style>\n<div class="row"><div class="item">A</div><div class="item">B</div><div class="item">C</div></div>'} /></>},
{id:'grid',icon:'5',title:'CSS Grid et responsive',content:<>{code('.grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 1rem;\n}\n@media (max-width: 700px) {\n  .grid { grid-template-columns: 1fr; }\n}') }<div className="note-box">Utilisez Grid pour organiser des zones en deux dimensions et Flexbox pour aligner des éléments sur un axe.</div></>}
]} prev={{to:'/html',label:'HTML5 Rappel'}} next={{to:'/js',label:'JavaScript Rappel'}} />; }
