import StudyPage from '../components/StudyPage';
import HtmlLab from '../components/HtmlLab';

const table = (head: string[], rows: Array<React.ReactNode[]>) => <div className="table-wrap"><table className="sti-table"><thead><tr>{head.map((cell) => <th key={cell}>{cell}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>;
const code = (text: string) => <pre className="sql-block">{text}</pre>;

export default function HtmlPage() {
  return <StudyPage accent="#ff8a65" glow="#ff8a6540" badge="HTML5 · STI" title="HTML5 — Rappel" subtitle="Structure, balises sémantiques, formulaires et intégration" toc={[{id:'structure',label:'Structure'},{id:'texte',label:'Texte'},{id:'liens',label:'Liens & médias'},{id:'formulaires',label:'Formulaires'},{id:'semantique',label:'Sémantique'}]} sections={[
    {id:'structure',icon:'1',title:'Structure d’une page HTML',content:<>{table(['Balise','Rôle','Exemple'],[[<code>&lt;!DOCTYPE html&gt;</code>,'Déclare le type du document',''],[<code>&lt;html&gt;</code>,'Racine du document',''],[<code>&lt;head&gt;</code>,'Métadonnées et ressources',''],[<code>&lt;body&gt;</code>,'Contenu visible',''],[<code>&lt;title&gt;</code>,'Titre de l’onglet','']])}{code('<!DOCTYPE html>\n<html lang="fr">\n  <head>\n    <meta charset="UTF-8">\n    <title>Ma page</title>\n  </head>\n  <body>\n    Contenu visible\n  </body>\n</html>')}</>},
    {id:'texte',icon:'2',title:'Texte et organisation',content:<>{table(['Balise','Description'],[[<code>&lt;h1&gt; à &lt;h6&gt;</code>,'Titres hiérarchiques'],[<code>&lt;p&gt;</code>,'Paragraphe'],[<code>&lt;strong&gt;</code>,'Texte important'],[<code>&lt;em&gt;</code>,'Texte mis en valeur'],[<code>&lt;ul&gt; / &lt;ol&gt;</code>,'Listes à puces ou numérotées'],[<code>&lt;li&gt;</code>,'Élément de liste']])}<HtmlLab initialCode={'<h3>Bienvenue en STI</h3>\n<p>Apprendre le web pas à pas.</p>\n<ul>\n  <li>HTML</li>\n  <li>CSS</li>\n</ul>'} /></>},
    {id:'liens',icon:'3',title:'Liens, images et médias',content:<>{table(['Balise','Attributs utiles','Rôle'],[[<code>&lt;a&gt;</code>,<><span className="pill">href</span></>,'Créer un lien'],[<code>&lt;img&gt;</code>,<><span className="pill">src</span><span className="pill">alt</span></>,'Afficher une image'],[<code>&lt;audio&gt;</code>,<><span className="pill">controls</span></>,'Lecteur audio'],[<code>&lt;video&gt;</code>,<><span className="pill">controls</span></>,'Lecteur vidéo']])}<div className="note-box">L’attribut <code>alt</code> décrit toujours l’image pour l’accessibilité.</div><HtmlLab initialCode={'<a href="https://example.com">Visiter le site</a>\n<br>\n<img src="https://placehold.co/240x100" alt="Image exemple">'} /></>},
    {id:'formulaires',icon:'4',title:'Formulaires',content:<>{table(['Élément','Attributs','Description'],[[<code>&lt;form&gt;</code>,<><span className="pill">action</span><span className="pill">method</span></>,'Conteneur du formulaire'],[<code>&lt;input&gt;</code>,<><span className="pill">type</span><span className="pill">name</span><span className="pill">required</span></>,'Champ de saisie'],[<code>&lt;label&gt;</code>,<><span className="pill">for</span></>,'Étiquette accessible'],[<code>&lt;button&gt;</code>,<><span className="pill">type</span></>,'Bouton d’action']])}<HtmlLab initialCode={'<form>\n  <label for="nom">Nom</label>\n  <input id="nom" type="text" placeholder="Votre nom">\n  <button type="button">Envoyer</button>\n</form>'} /></>},
    {id:'semantique',icon:'5',title:'Balises sémantiques HTML5',content:<>{table(['Balise','Utilisation'],[[<code>&lt;header&gt;</code>,'En-tête d’une page ou d’une section'],[<code>&lt;nav&gt;</code>,'Zone de navigation'],[<code>&lt;main&gt;</code>,'Contenu principal unique'],[<code>&lt;section&gt;</code>,'Section thématique'],[<code>&lt;article&gt;</code>,'Contenu autonome'],[<code>&lt;footer&gt;</code>,'Pied de page']])}<div className="note-box">La structure sémantique améliore la lisibilité du code, le référencement et l’accessibilité.</div></>}
  ]} next={{to:'/css',label:'CSS3 Rappel'}} />;
}
