import StudyPage from '../components/StudyPage';
import JsLab from '../components/JsLab';
const table = (head: string[], rows: Array<React.ReactNode[]>) => <div className="table-wrap"><table className="sti-table"><thead><tr>{head.map((cell) => <th key={cell}>{cell}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>;
const code = (text: string) => <pre className="sql-block">{text}</pre>;
export default function JsPage() { return <StudyPage accent="#fbbf24" glow="#fbbf2438" badge="JavaScript · STI" title="JavaScript — Rappel" subtitle="Variables, fonctions, objets, DOM et événements" toc={[{id:'variables',label:'Variables'},{id:'operateurs',label:'Opérateurs'},{id:'fonctions',label:'Fonctions'},{id:'dom',label:'DOM'},{id:'events',label:'Événements'}]} sections={[
{id:'variables',icon:'1',title:'Variables et types',content:<>{table(['Mot-clé','Description','Exemple'],[[<code>let</code>,'Valeur modifiable','let note = 15;'],[<code>const</code>,'Constante','const matiere = "JS";'],[<code>string</code>,'Chaîne de caractères','"Bonjour"'],[<code>number</code>,'Nombre entier ou décimal','3.14'],[<code>boolean</code>,'true ou false','note >= 10']])}<JsLab outId="js-vars" initialCode={'const note = 15;\nconsole.log(note >= 10 ? "Admis" : "Non admis");'} /></>},
{id:'operateurs',icon:'2',title:'Opérateurs et conditions',content:<>{table(['Opérateur','Rôle'],[[<code>===</code>,'Égalité stricte'],[<code>!==</code>,'Différence stricte'],[<code>&&</code>,'ET logique'],[<code>||</code>,'OU logique'],[<code>??</code>,'Valeur par défaut'],[<code>condition ? a : b</code>,'Ternaire']])}{code('if (note >= 10 && absent === false) {\n  console.log("Admis");\n} else {\n  console.log("À revoir");\n}')}</>},
{id:'fonctions',icon:'3',title:'Fonctions et tableaux',content:<>{code('const moyenne = (notes) => {\n  return notes.reduce((total, note) => total + note, 0) / notes.length;\n};\n\nconst notes = [12, 15, 9, 16];\nconsole.log(moyenne(notes));') }<JsLab outId="js-array" initialCode={'const matieres = ["HTML", "CSS", "JavaScript"];\nconsole.log(matieres.map((matiere, index) => `${index + 1}. ${matiere}`).join("\\n"));'} /></>},
{id:'dom',icon:'4',title:'Manipuler le DOM',content:<>{table(['Méthode','Rôle'],[[<code>querySelector()</code>,'Sélectionne le premier élément correspondant'],[<code>textContent</code>,'Modifie le texte'],[<code>classList.add()</code>,'Ajoute une classe CSS'],[<code>createElement()</code>,'Crée un élément'],[<code>append()</code>,'Insère un élément']])}{code('const titre = document.querySelector("h1");\ntitre.textContent = "Nouveau titre";\ntitre.classList.add("active");')}</>},
{id:'events',icon:'5',title:'Événements',content:<><JsLab outId="js-event" isBox initialCode={'const message = document.createElement("p");\nmessage.textContent = "Le bouton a été activé.";\nconst bouton = document.createElement("button");\nbouton.textContent = "Cliquez";\nbouton.onclick = () => console.log(message.textContent);\ndocument.body.append(bouton, message);'} /></>}
]} prev={{to:'/css',label:'CSS3 Rappel'}} next={{to:'/sql',label:'SQL Rappel'}} />; }
