import StudyPage from '../components/StudyPage';
const table = (head: string[], rows: Array<React.ReactNode[]>) => <div className="table-wrap"><table className="sti-table"><thead><tr>{head.map((cell) => <th key={cell}>{cell}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>;
const code = (text: string) => <pre className="php-block">{text}</pre>;
const example = (title: string, badge: string, source: string) => <div className="ex-card"><div className="ex-card-header"><span>{title}</span><span className="tag-badge">{badge}</span></div>{code(source)}</div>;
export default function PhpPage() { return <StudyPage accent="#c084fc" glow="#c084fc38" badge="PHP · STI" title="PHP — Rappel" subtitle="Types, opérateurs, fonctions, MySQLi et exemples complets" toc={[{id:'types',label:'Types'},{id:'operateurs',label:'Opérateurs'},{id:'fonctions',label:'Fonctions'},{id:'superglobales',label:'Superglobales'},{id:'mysqli',label:'MySQLi'},{id:'exemples',label:'Exemples'}]} sections={[
{id:'types',icon:'1',title:'Types d’objets',content:<>{table(['Type','Description','Exemple'],[[<code>int</code>,'Entier','$n = 42;'],[<code>float</code>,'Réel','$x = 3.14;'],[<code>string</code>,'Chaîne de caractères','$s = "Bonjour";'],[<code>bool</code>,'true / false','$ok = true;'],[<code>array</code>,'Tableau','$t = [1,2,3];']])}</>},
{id:'operateurs',icon:'2',title:'Opérateurs',content:<>{table(['Famille','Opérateurs'],[[<strong>Arithmétiques</strong>,<code>+ &nbsp; - &nbsp; * &nbsp; / &nbsp; %</code>],[<strong>Logiques</strong>,<code>&&nbsp; &&nbsp; || &nbsp; !</code>],[<strong>Comparaison</strong>,<code>== &nbsp; &lt;&gt; &nbsp; &lt; &nbsp; &gt; &nbsp; &gt;=</code>],[<strong>Autres</strong>,<code>= &nbsp; .</code>]])}{code('$note = 15;\nif ($note >= 10) {\n  echo "Admis";\n}')}</>},
{id:'fonctions',icon:'3',title:'Fonctions PHP',content:<>{table(['Fonction','Description','Exemple'],[[<code>strlen($ch)</code>,'Retourne la longueur','strlen("Bonjour") → 7'],[<code>strtoupper($ch)</code>,'Convertit en majuscules','strtoupper("hello")'],[<code>trim($ch)</code>,'Supprime les espaces','trim(" Bonjour ")'],[<code>count($tab)</code>,'Compte les éléments','count([1,2,3]) → 3'],[<code>date($format)</code>,'Formate la date','date("d/m/Y")']])}</>},
{id:'superglobales',icon:'4',title:'Variables superglobales',content:<>{table(['Variable','Description','Exemple'],[[<code>$_GET</code>,'Valeurs dans l’URL','$_GET["nom"]'],[<code>$_POST</code>,'Valeurs d’un formulaire','$_POST["email"]'],[<code>$_SESSION</code>,'Données de session','$_SESSION["user"]'],[<code>$_SERVER</code>,'Informations serveur','$_SERVER["REQUEST_METHOD"]']])}</>},
{id:'mysqli',icon:'5',title:'Fonctions PHP pour MySQLi',content:<>{table(['Fonction','Description'],[[<code>mysqli_connect()</code>,'Établit une connexion'],[<code>mysqli_query()</code>,'Envoie une requête SQL'],[<code>mysqli_fetch_array()</code>,'Retourne une ligne'],[<code>mysqli_num_rows()</code>,'Compte les lignes'],[<code>mysqli_close()</code>,'Ferme la connexion']])}</>},
{id:'exemples',icon:'6',title:'Exemples complets — PHP & MySQLi',content:<>{example('Connexion à la base de données','mysqli_connect · die','<?php\n$conn = mysqli_connect("localhost", "root", "", "ecole");\nif (!$conn) die(mysqli_connect_error());\necho "Connexion réussie !";\n?>')}{example('Sélectionner et afficher des données','mysqli_query · mysqli_fetch_array','$sql = "SELECT id, nom, prenom, note FROM eleve ORDER BY nom ASC";\n$result = mysqli_query($conn, $sql);\nwhile ($ligne = mysqli_fetch_array($result)) {\n  echo $ligne["nom"] . " " . $ligne["prenom"];\n}')}{example('Insérer une donnée','INSERT · $_POST','$sql = "INSERT INTO eleve (nom, prenom, note)\n        VALUES (\'Trabelsi\', \'Amine\', 15)";\nmysqli_query($conn, $sql);')}</>}
]} prev={{to:'/sql',label:'SQL Rappel'}} next={{to:'/',label:'Retour à l’accueil'}} />; }
