import StudyPage from '../components/StudyPage';
const table = (head: string[], rows: Array<React.ReactNode[]>) => <div className="table-wrap"><table className="sti-table"><thead><tr>{head.map((cell) => <th key={cell}>{cell}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>;
const code = (text: string) => <pre className="sql-block">{text}</pre>;
export default function SqlPage() { return <StudyPage accent="#22c55e" glow="#22c55e38" badge="SQL · STI" title="SQL — Rappel" subtitle="Créer, interroger et modifier les données" toc={[{id:'ddl',label:'DDL'},{id:'select',label:'SELECT'},{id:'filtres',label:'Filtres'},{id:'jointures',label:'Jointures'},{id:'crud',label:'CRUD'}]} sections={[
{id:'ddl',icon:'1',title:'Créer une table',content:<>{table(['Instruction','Rôle'],[[<code>CREATE DATABASE</code>,'Crée une base de données'],[<code>CREATE TABLE</code>,'Crée une table'],[<code>ALTER TABLE</code>,'Modifie une table'],[<code>DROP TABLE</code>,'Supprime une table']])}{code('CREATE TABLE eleve (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  nom VARCHAR(60) NOT NULL,\n  prenom VARCHAR(60) NOT NULL,\n  note DECIMAL(4,2)\n);')}</>},
{id:'select',icon:'2',title:'Requêtes SELECT',content:<>{code('SELECT id, nom, prenom, note\nFROM eleve\nORDER BY nom ASC;')}{table(['Clause','Utilisation'],[[<code>SELECT</code>,'Colonnes à afficher'],[<code>FROM</code>,'Table source'],[<code>WHERE</code>,'Condition de filtrage'],[<code>ORDER BY</code>,'Tri du résultat'],[<code>LIMIT</code>,'Limite de lignes']])}</>},
{id:'filtres',icon:'3',title:'Filtrer et agréger',content:<>{code('SELECT classe, AVG(note) AS moyenne, COUNT(*) AS effectif\nFROM eleve\nWHERE note >= 10\nGROUP BY classe\nHAVING AVG(note) >= 12;')}{table(['Fonction','Rôle'],[[<code>COUNT()</code>,'Compte les lignes'],[<code>SUM()</code>,'Additionne une colonne'],[<code>AVG()</code>,'Calcule la moyenne'],[<code>MIN() / MAX()</code>,'Minimum et maximum']])}</>},
{id:'jointures',icon:'4',title:'Jointures',content:<>{code('SELECT e.nom, e.prenom, c.nom AS classe\nFROM eleve e\nINNER JOIN classe c ON c.id = e.classe_id\nWHERE c.niveau = "Terminale";') }<div className="note-box">Une jointure relie les lignes de plusieurs tables grâce à une colonne commune.</div></>},
{id:'crud',icon:'5',title:'Opérations CRUD',content:<>{code('INSERT INTO eleve (nom, prenom, note)\nVALUES ("Trabelsi", "Amine", 15);\n\nUPDATE eleve SET note = 18 WHERE id = 3;\n\nDELETE FROM eleve WHERE id = 3;') }<div className="note-box">Avant un UPDATE ou un DELETE, testez toujours votre condition avec un SELECT.</div></>}
]} prev={{to:'/js',label:'JavaScript Rappel'}} next={{to:'/php',label:'PHP Rappel'}} />; }
